/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExperienceRouteImport } from './routes/experience'
import { Route as ProjectsRouteRouteImport } from './routes/projects/route'
import { Route as PlaygroundRouteRouteImport } from './routes/playground/route'
import { Route as InterestsRouteRouteImport } from './routes/interests/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsIndexRouteImport } from './routes/projects/index'
import { Route as PlaygroundIndexRouteImport } from './routes/playground/index'
import { Route as InterestsIndexRouteImport } from './routes/interests/index'
import { Route as ProjectsSlugRouteImport } from './routes/projects/$slug'
import { Route as PlaygroundWhoamiRouteImport } from './routes/playground/whoami'
import { Route as PlaygroundSysinfoRouteImport } from './routes/playground/sysinfo'
import { Route as PlaygroundSpaceRouteImport } from './routes/playground/space'
import { Route as PlaygroundGamesRouteImport } from './routes/playground/games'
import { Route as InterestsWatchingRouteImport } from './routes/interests/watching'
import { Route as InterestsReadingRouteImport } from './routes/interests/reading'

const ExperienceRoute = ExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRouteRoute = ProjectsRouteRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaygroundRouteRoute = PlaygroundRouteRouteImport.update({
  id: '/playground',
  path: '/playground',
  getParentRoute: () => rootRouteImport,
} as any)
const InterestsRouteRoute = InterestsRouteRouteImport.update({
  id: '/interests',
  path: '/interests',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsIndexRoute = ProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const PlaygroundIndexRoute = PlaygroundIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const InterestsIndexRoute = InterestsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProjectsRouteRoute,
} as any)
const PlaygroundWhoamiRoute = PlaygroundWhoamiRouteImport.update({
  id: '/whoami',
  path: '/whoami',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundSysinfoRoute = PlaygroundSysinfoRouteImport.update({
  id: '/sysinfo',
  path: '/sysinfo',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundSpaceRoute = PlaygroundSpaceRouteImport.update({
  id: '/space',
  path: '/space',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const PlaygroundGamesRoute = PlaygroundGamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => PlaygroundRouteRoute,
} as any)
const InterestsWatchingRoute = InterestsWatchingRouteImport.update({
  id: '/watching',
  path: '/watching',
  getParentRoute: () => InterestsRouteRoute,
} as any)
const InterestsReadingRoute = InterestsReadingRouteImport.update({
  id: '/reading',
  path: '/reading',
  getParentRoute: () => InterestsRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/interests': typeof InterestsRouteRouteWithChildren
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/interests/reading': typeof InterestsReadingRoute
  '/interests/watching': typeof InterestsWatchingRoute
  '/playground/games': typeof PlaygroundGamesRoute
  '/playground/space': typeof PlaygroundSpaceRoute
  '/playground/sysinfo': typeof PlaygroundSysinfoRoute
  '/playground/whoami': typeof PlaygroundWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/interests/': typeof InterestsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/experience': typeof ExperienceRoute
  '/interests/reading': typeof InterestsReadingRoute
  '/interests/watching': typeof InterestsWatchingRoute
  '/playground/games': typeof PlaygroundGamesRoute
  '/playground/space': typeof PlaygroundSpaceRoute
  '/playground/sysinfo': typeof PlaygroundSysinfoRoute
  '/playground/whoami': typeof PlaygroundWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/interests': typeof InterestsIndexRoute
  '/playground': typeof PlaygroundIndexRoute
  '/projects': typeof ProjectsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/interests': typeof InterestsRouteRouteWithChildren
  '/playground': typeof PlaygroundRouteRouteWithChildren
  '/projects': typeof ProjectsRouteRouteWithChildren
  '/experience': typeof ExperienceRoute
  '/interests/reading': typeof InterestsReadingRoute
  '/interests/watching': typeof InterestsWatchingRoute
  '/playground/games': typeof PlaygroundGamesRoute
  '/playground/space': typeof PlaygroundSpaceRoute
  '/playground/sysinfo': typeof PlaygroundSysinfoRoute
  '/playground/whoami': typeof PlaygroundWhoamiRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/interests/': typeof InterestsIndexRoute
  '/playground/': typeof PlaygroundIndexRoute
  '/projects/': typeof ProjectsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/interests'
    | '/playground'
    | '/projects'
    | '/experience'
    | '/interests/reading'
    | '/interests/watching'
    | '/playground/games'
    | '/playground/space'
    | '/playground/sysinfo'
    | '/playground/whoami'
    | '/projects/$slug'
    | '/interests/'
    | '/playground/'
    | '/projects/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/experience'
    | '/interests/reading'
    | '/interests/watching'
    | '/playground/games'
    | '/playground/space'
    | '/playground/sysinfo'
    | '/playground/whoami'
    | '/projects/$slug'
    | '/interests'
    | '/playground'
    | '/projects'
  id:
    | '__root__'
    | '/'
    | '/interests'
    | '/playground'
    | '/projects'
    | '/experience'
    | '/interests/reading'
    | '/interests/watching'
    | '/playground/games'
    | '/playground/space'
    | '/playground/sysinfo'
    | '/playground/whoami'
    | '/projects/$slug'
    | '/interests/'
    | '/playground/'
    | '/projects/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InterestsRouteRoute: typeof InterestsRouteRouteWithChildren
  PlaygroundRouteRoute: typeof PlaygroundRouteRouteWithChildren
  ProjectsRouteRoute: typeof ProjectsRouteRouteWithChildren
  ExperienceRoute: typeof ExperienceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/experience': {
      id: '/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof ExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playground': {
      id: '/playground'
      path: '/playground'
      fullPath: '/playground'
      preLoaderRoute: typeof PlaygroundRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interests': {
      id: '/interests'
      path: '/interests'
      fullPath: '/interests'
      preLoaderRoute: typeof InterestsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/': {
      id: '/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof ProjectsIndexRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/playground/': {
      id: '/playground/'
      path: '/'
      fullPath: '/playground/'
      preLoaderRoute: typeof PlaygroundIndexRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/interests/': {
      id: '/interests/'
      path: '/'
      fullPath: '/interests/'
      preLoaderRoute: typeof InterestsIndexRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof ProjectsRouteRoute
    }
    '/playground/whoami': {
      id: '/playground/whoami'
      path: '/whoami'
      fullPath: '/playground/whoami'
      preLoaderRoute: typeof PlaygroundWhoamiRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/sysinfo': {
      id: '/playground/sysinfo'
      path: '/sysinfo'
      fullPath: '/playground/sysinfo'
      preLoaderRoute: typeof PlaygroundSysinfoRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/space': {
      id: '/playground/space'
      path: '/space'
      fullPath: '/playground/space'
      preLoaderRoute: typeof PlaygroundSpaceRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/playground/games': {
      id: '/playground/games'
      path: '/games'
      fullPath: '/playground/games'
      preLoaderRoute: typeof PlaygroundGamesRouteImport
      parentRoute: typeof PlaygroundRouteRoute
    }
    '/interests/watching': {
      id: '/interests/watching'
      path: '/watching'
      fullPath: '/interests/watching'
      preLoaderRoute: typeof InterestsWatchingRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
    '/interests/reading': {
      id: '/interests/reading'
      path: '/reading'
      fullPath: '/interests/reading'
      preLoaderRoute: typeof InterestsReadingRouteImport
      parentRoute: typeof InterestsRouteRoute
    }
  }
}

interface InterestsRouteRouteChildren {
  InterestsReadingRoute: typeof InterestsReadingRoute
  InterestsWatchingRoute: typeof InterestsWatchingRoute
  InterestsIndexRoute: typeof InterestsIndexRoute
}

const InterestsRouteRouteChildren: InterestsRouteRouteChildren = {
  InterestsReadingRoute: InterestsReadingRoute,
  InterestsWatchingRoute: InterestsWatchingRoute,
  InterestsIndexRoute: InterestsIndexRoute,
}

const InterestsRouteRouteWithChildren = InterestsRouteRoute._addFileChildren(
  InterestsRouteRouteChildren,
)

interface PlaygroundRouteRouteChildren {
  PlaygroundGamesRoute: typeof PlaygroundGamesRoute
  PlaygroundSpaceRoute: typeof PlaygroundSpaceRoute
  PlaygroundSysinfoRoute: typeof PlaygroundSysinfoRoute
  PlaygroundWhoamiRoute: typeof PlaygroundWhoamiRoute
  PlaygroundIndexRoute: typeof PlaygroundIndexRoute
}

const PlaygroundRouteRouteChildren: PlaygroundRouteRouteChildren = {
  PlaygroundGamesRoute: PlaygroundGamesRoute,
  PlaygroundSpaceRoute: PlaygroundSpaceRoute,
  PlaygroundSysinfoRoute: PlaygroundSysinfoRoute,
  PlaygroundWhoamiRoute: PlaygroundWhoamiRoute,
  PlaygroundIndexRoute: PlaygroundIndexRoute,
}

const PlaygroundRouteRouteWithChildren = PlaygroundRouteRoute._addFileChildren(
  PlaygroundRouteRouteChildren,
)

interface ProjectsRouteRouteChildren {
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ProjectsIndexRoute: typeof ProjectsIndexRoute
}

const ProjectsRouteRouteChildren: ProjectsRouteRouteChildren = {
  ProjectsSlugRoute: ProjectsSlugRoute,
  ProjectsIndexRoute: ProjectsIndexRoute,
}

const ProjectsRouteRouteWithChildren = ProjectsRouteRoute._addFileChildren(
  ProjectsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InterestsRouteRoute: InterestsRouteRouteWithChildren,
  PlaygroundRouteRoute: PlaygroundRouteRouteWithChildren,
  ProjectsRouteRoute: ProjectsRouteRouteWithChildren,
  ExperienceRoute: ExperienceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
